{{- if not (empty .Values.fest_dynamic_products) }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-stateful-kafka-ui
  labels:
    dynamic: "true"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      gitlab:
        project: '{{ $.Values.dynamic_stands.gitlab_project_id }}'
        api: '{{ $.Values.dynamic_stands.gitlab_api_url }}'
        tokenRef:
          secretName: '{{ $.Values.dynamic_stands.tokenRef.secretName }}'
          key: '{{ $.Values.dynamic_stands.tokenRef.key }}'
        labels:
        - stateful/kafka-ui
        pullRequestState: opened
      requeueAfterSeconds: {{ $.Values.dynamic_stands.requeueAfterSeconds }}
      filters:
        - branchMatch: "^dyn/.*"
  template:
    metadata:
      name: 'stateful-{{ `{{ regexReplaceAll "/|_|\\." (.branch | substr 4 19 | lower) "-" | trimSuffix "-" }}` }}-kafka-ui'
      labels:
        branch: '{{ `{{ .branch_slug }}` }}'
        dynamic: "true"
        type: "kafka-ui"
    spec:
      source:
        repoURL: '{{ $.Values.dynamic_stands.extraCharts.kafka_ui.repoURL }}'
        path: .
        targetRevision: '{{ $.Values.dynamic_stands.extraCharts.kafka_ui.targetRevision }}'
        helm:
          valuesObject:
            dnsSuffix: '{{ $.Values.dns_suffix }}'
            epic: '{{ `-{{ regexReplaceAll "/|_|\\." (.branch | substr 4 19 | lower) "-" | trimSuffix "-" }}` }}'
          valueFiles:
            - dyn.yaml
            {{- range $.Values.dynamic_stands.extraCharts.kafka_ui.extraValuesFiles }}
            - {{ . }}
            {{- end }}
      project: dynamic
      destination:
        server: https://kubernetes.default.svc
        namespace: 'stateful-{{ `{{ regexReplaceAll "/|_|\\." (.branch | substr 4 19 | lower) "-" | trimSuffix "-" }}` }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
