{{- range $key, $val := .Values.gitlab_repos }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-{{ $key }}
  namespace: argocd
spec:
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store
  target:
    name: argocd-repo-creds-{{ $key }}
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ $val.url }}
        username: {{ $.Values.gitlab_secrets.username }}
        password: "{{ "{{ .password | toString }}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ $.Values.gitlab_secrets.path }}
        property: {{ $key }}
{{- end }}
