{{ range $i := until (int .Values.clusters_shard_count) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-{{ $i }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    type: argocd-workaround
type: Opaque
stringData:
  name: cluster-{{ $i }}
  server: https://cluster-{{ $i }}.argocd.svc
  shard: "{{ $i }}"
  config: |
    {
      "execProviderConfig": {
        "command": "bash",
        "args": [
          "-c",
          "echo -n '{\"apiVersion\":\"client.authentication.k8s.io/v1\",\"kind\":\"ExecCredential\",\"status\":{\"token\":\"'; cat /var/run/secrets/kubernetes.io/serviceaccount/token; echo -n '\"}}'"
        ],
        "apiVersion": "client.authentication.k8s.io/v1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "serverName": "{{- $.Values.service.externalName -}}",
        "caData": "{{- $.Values.kube_api_ca | b64enc -}}"
      }
    }
{{ end }}
