{{- range $k, $v := .Values.fest_products }}
{{- if $v.data }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $k }}-spark-sa
  namespace: {{ $k }}{{ $.Values.namespace_postfix | default "" }}
{{- end }}
{{- end }}
