{{- range $key, $val := .Values.fest_products }}
{{- if not $val.disableESO }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $key }}{{ if $val.integration }}-integration{{ end }}-secret-store
  namespace: {{ $key }}{{ if $val.integration }}-integration{{ end }}
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: {{ $.Values.vault_mountPath }}
          role: {{ $.Values.company }}_{{ $val.department | default $.Values.department }}_{{ $key }}_{{ $.Values.environment_name }}
          serviceAccountRef:
            name: sa-{{ $key }}-{{ $.Values.environment_name }}-eso
      path: codefest
      server: {{ $.Values.vault_url }}
      version: v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ $key }}-{{ $.Values.environment_name }}-eso
  namespace: {{ $key }}{{ if $val.integration }}-integration{{ end }}
{{- end }}
{{- end }}
