{{- $values := .Values -}}
{{- if $values.regcred_vault_path }}
{{- range $key, $val := .Values.fest_products }}
{{- if not (or $val.disableESO $val.disableRegcred) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-{{ $key }}
  namespace: {{ $key }}{{ if $val.integration }}-integration{{ end }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ $key }}{{ if $val.integration }}-integration{{ end }}-secret-store
  target:
    name: regcred
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  dataFrom:
    - extract:
        key: {{ $values.regcred_vault_path }}
{{- end }}
{{- end }}
{{- end }}
