{{- range $key, $val := ((.Values.git).credTpl).templateList }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-cred-tpl-{{ $key }}
  namespace: argocd
spec:
  secretStoreRef:
    kind: SecretStore
    name: argocd-secret-store
  target:
    name: argocd-cred-tpl-{{ $key }}
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: {{ $val.urlPrefix }}
        username: {{ (($.Values.git).credTpl).username }}
        password: "{{ "{{ .password | toString }}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: {{ (($.Values.git).credTpl).passwdVaultPath }}
        property: {{ $key }}
{{- end }}
